// <auto-generated />
namespace Clinica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AggiungiRelazioneTraAnimaleEVisita : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiungiRelazioneTraAnimaleEVisita));
        
        string IMigrationMetadata.Id
        {
            get { return "202412181317057_AggiungiRelazioneTraAnimaleEVisita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
